insert into movie(name, genre, url_stream) values('Jurassic Park', 'Ficción', 'https://cuevana3.ch/282/jurassic-park')
insert into movie(name, genre, url_stream) values('Harry Potter y las Reliquias de la muerte parte 1', 'Aventuras', 'https://cuevana2.io/titulo/harry-potter-y-las-reliquias-de-la-muerte-1a-parte/')
insert into movie(name, genre, url_stream) values('Transformers el lado oscuro de la luna', 'Ficcion', 'https://www.cuevanahd.net/pelicula/transformers-3-el-lado-oscuro-de-la-luna/')
insert into movie(name, genre, url_stream) values('Buscando a Nemo', 'Infantil', 'https://v3.cuevana.pro/pelicula/buscando-a-nemo')
insert into movie(name, genre, url_stream) values('La vida es bella', 'Drama', 'https://www.cuevanahd.net/pelicula/la-vida-es-bella/')
insert into movie(name, genre, url_stream) values('Hotel Transylvania', 'Infantil', 'https://ver.cuevana3.fan/pelicula/hotel-transylvania/')
insert into movie(name, genre, url_stream) values('Intensamente', 'Animada', 'https://cuevana3.ch/910/intensa-mente')
insert into movie(name, genre, url_stream) values('El rey leon', 'Animada', 'https://ww2.cuevana3.me/18728/el-rey-leon')